#!/bin/sh
uci set network.lan.ipaddr="192.168.1.1"
uci commit network
/etc/init.d/network restart
sed -i "/^DISTRIB_DESCRIPTION='/s/'$/ Compiled by 沉默の金'/" /etc/openwrt_release
[ -d "/etc/init.d" ] && chmod +x /etc/init.d/*
uci commit
exit 0

